apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: applications
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./kubernetes/applications/undo-lr4j
  prune: true
  validation: client
  dependsOn:
    - name: infrastructure
  sourceRef:
    kind: GitRepository
    name: flux-system