apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: aws-load-balancer-controller-crds
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./stable/aws-load-balancer-controller/crds
  prune: true
  sourceRef:
    kind: GitRepository
    name: aws-eks-charts
  validation: client
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: aws-load-balancer-controller
  namespace: kube-system
spec:
  releaseName: aws-load-balancer-controller
  chart:
    spec:
      chart: aws-load-balancer-controller
      sourceRef:
        kind: HelmRepository
        name: aws-eks
        namespace: flux-system
      version: "1.2.6"
  interval: 5m0s
  install:
    remediation:
      retries: 3
  # https://github.com/aws/eks-charts/tree/master/stable/aws-load-balancer-controller
  values:
    clusterName: undo-eks
    serviceAccount:
      create: false
      name: aws-load-balancer-controller