apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - efs-driver.yaml
  - aws-eks-sources.yaml
  - kubernetes-sigs-sources.yaml
  - https://github.com/kubernetes-sigs/metrics-server/releases/download/v0.6.1/components.yaml
  - aws-load-balancer.yaml