version: "3"

services:
   demo-service:
    build:
      context: .
    image: demo-service:latest
    environment:
      - LR4J_DIRECTORY=/opt/payara/replay
    volumes:
      - "./replay:/opt/payara/replay"
    ports:
      - "8080:8080"
      - "9001:9001"
