apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: parts-service-default
  namespace: demo
spec:
  interval: 5m0s
  path: ./services/parts-service/k8s
  prune: true
  targetNamespace: demo
  sourceRef:
    kind: GitRepository
    name: parts-service
  validation: client
  # we supply an inline patch for the deployment
  patchesStrategicMerge:
    - apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: parts-service
      spec:
        replicas: 2
        template:
          spec:
            containers:
            - name: parts-service
              image: lreimer/parts-service:default
              imagePullPolicy: Always
    - apiVersion: v1
      kind: Service
      metadata:
        name: parts-service
      spec:
        type: LoadBalancer