apiVersion: apps/v1
kind: Deployment
metadata:
  name: parts-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: parts-service
  template:
    metadata:
      labels:
        app: parts-service
    spec:
      containers:
      - name: parts-service
        image: lreimer/parts-service
        resources:
          requests:
            memory: "512Mi"
            cpu: "0.5"
          limits:
            memory: "1024Mi"
            cpu: "2"
        env:
          - name: VEHICLE_BASE_URI
            value: http://vehicle-service:8081/api
        ports:
        - name: http
          containerPort: 8080
