apiVersion: v1
kind: Service
metadata:
  name: parts-service
spec:
  selector:
    app: parts-service
  type: ClusterIP
  sessionAffinity: None
  ports:
    - protocol: TCP
      port: 8080
      targetPort: http
